
export function createPlanet(size, textureUrl, emissive = 0x000000, tl) {
    const geometry = new THREE.SphereGeometry(size, 32, 32);
    const texture = tl.load(textureUrl);
    const material = new THREE.MeshPhongMaterial({
        map: texture,
        emissive: emissive,
        emissiveIntensity: 0.5
    });
    const planet = new THREE.Mesh(geometry, material);
    planet.castShadow = true;
    planet.receiveShadow = true;
    return planet;
}

export const orbitalElements = {
    mercury: {
        semiMajorAxis: 57.91,
        eccentricity: 0.2056,
        inclination: THREE.MathUtils.degToRad(7.005),
        longitudeOfAscendingNode: THREE.MathUtils.degToRad(48.331),
        argumentOfPeriapsis: THREE.MathUtils.degToRad(29.124),
        meanAnomalyAtEpoch: THREE.MathUtils.degToRad(174.796),
        epoch: 2451545.0,
        link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQHHhttyRZnbpliW8ftwD7BQUZs6aTPmI7eQ&s',
        name: 'Mercúrio',
        sizeOf: '10', //1.5
        distance: '58 milhões de km'
    },
    venus: {
        semiMajorAxis: 108.2,
        eccentricity: 0.0067,
        inclination: THREE.MathUtils.degToRad(3.39),
        longitudeOfAscendingNode: THREE.MathUtils.degToRad(76.680),
        argumentOfPeriapsis: THREE.MathUtils.degToRad(131.532),
        meanAnomalyAtEpoch: THREE.MathUtils.degToRad(50.115),
        epoch: 2451545.0,
        link: 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Solarsystemscope_texture_8k_venus_surface.jpg',
        name: 'Vênus',
        sizeOf: '10', //3.7
        distance: '108 milhões de km'
    },
    earth: {
        semiMajorAxis: 149.6,  // Unidade: milhões de km
        eccentricity: 0.0167,
        inclination: THREE.MathUtils.degToRad(0.00005),  // Aproximado, em radianos
        longitudeOfAscendingNode: THREE.MathUtils.degToRad(-11.26064),  // Graus convertidos em radianos
        argumentOfPeriapsis: THREE.MathUtils.degToRad(114.20783),  // Graus convertidos em radianos
        meanAnomalyAtEpoch: THREE.MathUtils.degToRad(358.617),  // Graus convertidos em radianos
        epoch: 2451545.0, // Tempo juliano
        link: 'https://raw.githubusercontent.com/mrdoob/three.js/master/examples/textures/planets/earth_atmos_2048.jpg',
        sizeOf: '10', //3.9
        name:```'Earth',
        Size: ' Diameter of about 12,742 km, the largest of the rocky planets',
        Mass: ' About 5.97 x 10²⁴ kg',
        Distance_from_the_Sun: 'Approximately 149.6 million km (1 AU)',
        Distance_from_the_Moon: ' About 384,400 km',
        Composition: 'Earth has a solid inner core of iron and nickel, a liquid outer core, a silicate mantle, and a solid crust',
        Atmosphere: 'Earth’s atmosphere is composed of 78% nitrogen, 21% oxygen, and traces of other gases like carbon dioxide and argon',
        Orbit: ' Earth takes 365.25 days to orbit the Sun. It has a 23.5° axial tilt, causing seasons, and rotates once every 24 hours',
        Natural_satellites: ' Earth has one satellite, the Moon',
        Magnetic_field: ' Earth has a strong magnetic field generated by the movement of liquid iron in its outer core, protecting it from solar radiation',```
    },
    moon: {
        semiMajorAxis: 0.384,  // Unidade: milhões de km
        eccentricity: 0.0549,
        inclination: THREE.MathUtils.degToRad(5.145),  // Aproximado, em radianos
        longitudeOfAscendingNode: THREE.MathUtils.degToRad(125.08),  // Graus convertidos em radianos
        argumentOfPeriapsis: THREE.MathUtils.degToRad(318.15),  // Graus convertidos em radianos
        meanAnomalyAtEpoch: THREE.MathUtils.degToRad(115.365),  // Graus convertidos em radianos
        epoch: 2451545.0, // Tempo juliano
        link: 'https://raw.githubusercontent.com/mrdoob/three.js/master/examples/textures/planets/moon_1024.jpg',
        sizeOf: '3',
        distance: '384 mil km',
        name: ```'Lua',
        Size: 'Approximately 3,474 km, making it the fifth-largest natural satellite in the Solar System',
        Mass: 'About 7.35 x 10²² kg, or roughly 1.2% of Earth\s mass',
        Distance_from_Earth: 'Around 384,400 km. This distance varies slightly due to its elliptical orbit',
        Composition: 'The Moon is primarily composed of oxygen-rich, silicon, magnesium, iron, calcium, and aluminum rocks. Its interior is divided into',  
        Crust: 'Made of basalt and anorthosite',
        Mantle: 'Composed of magnesium- and iron-rich minerals',
        Core: 'Made of iron with small traces of sulfur and nickel, but much smaller than Earth’s core',
        Atmosphere: 'The Moon has an extremely thin exosphere, containing trace amounts of gases such as hydrogen, helium, neon, and argon. It is so thin that it offers no protection against solar radiation or meteorite impacts, often referred to as "no atmosphere',
        Orbital_period: 'The Moon takes approximately 27.3 Earth days to complete one orbit around the Earth (a sidereal month)',
        Rotation: 'The Moon is in synchronous rotation with Earth, meaning the same side of the Moon always faces us (the "near side"). The opposite side is known as the "far side" of the Moon',
        Inclination: 'Its orbit is tilted by about 5.1 degrees relative to the plane of Earth\s orbit',
        Gravity: 'Lunar gravity is about 1/6th of Earth\s gravity, or approximately 16.5% of Earth\s gravity. This means objects weigh significantly less on the Moon than on Earth',
        Surface:'The lunar surface is marked by impact craters, basaltic plains (lunar maria), mountains, and valleys. The craters result from meteorite impacts over billions of years since the Moon lacks an atmosphere to protect it> < The surface is covered by a thin layer of regolith, a mixture of rock fragments and dust created by meteorite impacts',
        Natural_Satellites: 'The Moon has no natural satellites of its own',
        Magnetic Field: 'The Moon does not have a significant global magnetic field, although some localized regions exhibit residual magnetism, which has been detected in lunar rock samples',```
       
    },
    venus: {
        semiMajorAxis: 108.2,
        eccentricity: 0.0067,
        inclination: THREE.MathUtils.degToRad(3.39),
        longitudeOfAscendingNode: THREE.MathUtils.degToRad(76.680),
        argumentOfPeriapsis: THREE.MathUtils.degToRad(131.532),
        meanAnomalyAtEpoch: THREE.MathUtils.degToRad(50.115),
        epoch: 2451545.0,
        sizeOf: '10',
        link: 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Solarsystemscope_texture_8k_venus_surface.jpg',
        name: ```'Vênus',
        Size: ' Diameter of approximately 12,104 km, just slightly smaller than Earth\s', 
        Mass: 'About 4.87 x 10²⁴ kg, or about 82% of Earth\s mass',
        Distance_from_the_Sun: 'Approximately 108.2 million km (0.72 AU)',
        Distance_from_Earth: ' Around 38 million km, although it varies significantly',
        Composition: ' Composed mainly of rocks and metals, similar to Earth, with a metallic core of iron and nickel, a silicate mantle, and a thin rocky crust',
        Atmosphere: ' Venus has a very dense atmosphere, mostly composed of carbon dioxide (95.5%) and nitrogen (3.5%). It is known for its extreme greenhouse effect, leading to surface temperatures around 462°C',
        Orbit: 'Orbital period: Venus takes 225 Earth days to orbit the Sun. Rotation: Venus rotates very slowly, taking 243 Earth days to complete one rotation, and it rotates in a retrograde direction',
        Natural_satellites: 'None',
        Magnetic_field: 'Venus has no significant magnetic field, likely due to its slow rotation',```
    },
    mercury: {
        semiMajorAxis: 57.91,
        eccentricity: 0.2056,
        inclination: THREE.MathUtils.degToRad(7.005),
        longitudeOfAscendingNode: THREE.MathUtils.degToRad(48.331),
        argumentOfPeriapsis: THREE.MathUtils.degToRad(29.124),
        meanAnomalyAtEpoch: THREE.MathUtils.degToRad(174.796),
        epoch: 2451545.0,
        sizeOf: '10',
        link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQHHhttyRZnbpliW8ftwD7BQUZs6aTPmI7eQ&s',
        name: ```'Mercury',
        Size: ' Diameter of approximately 4,880 km', //1.5
        Mass: ' About 3.3 x 10²³ kg',
        Distance_from_the_Sun: ' Approximately 57.9 million km',
        Distance_from_Earth: 'The minimum distance is about 77 million km',
        Composition: 'Composed of metals and silicates. Its core is relatively large, made of iron, occupying about 75% of the planet radius',
        Atmosphere: ' Mercury has an exosphere composed mainly of atoms of oxygen, sodium, hydrogen, helium, and potassium. It does not have a thick atmosphere, which means it does not retain heat and experiences extreme temperature variations',
        Orbit: ' Orbital period: Mercury completes a revolution around the Sun in about 88 Earth days. Its orbit is highly eccentric, varying between 46 million km (perihelion) and 70 million km (aphelion) from the Sun',
        Natural_satellites:' None',
        Magnetic_field: 'Mercury has a very weak magnetic field, about 1% as strong as Earth'```
    },
    mars: {
        semiMajorAxis: 227.9,
        eccentricity: 0.0934,
        inclination: THREE.MathUtils.degToRad(1.85),
        longitudeOfAscendingNode: THREE.MathUtils.degToRad(49.558),
        argumentOfPeriapsis: THREE.MathUtils.degToRad(286.537),
        meanAnomalyAtEpoch: THREE.MathUtils.degToRad(19.412),
        epoch: 2451545.0,
        sizeOf: '10',
        link:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQc0ELDdWdnToVXeznMHPNmZPjB9-jKy1p68Q&s',
        name: ```'Mars',
        Size: 'Diameter of approximately 6,779 km, about half of Earth\s diameter', //2.1
        Mass: ' About 6.42 x 10²³ kg, or about 10.7% of Earth\s mass,
        Distance_from_the_Sun: 'Approximately 227.9 million km (1.52 AU)',
        Distance_from_Earth: ' About 54.6 million km, depending on orbital positions',
        Composition: ' Mars has a core of iron, nickel, and sulfur, a rocky mantle, and a surface rich in iron oxides, giving it a red color.',
        Atmosphere: 'Mars atmosphere is thin, composed mainly of carbon dioxide (95%) with some nitrogen (2.6%) and argon (1.9%). The low atmospheric pressure prevents stable liquid water',
        Orbit: ' Orbital period: Mars takes 687 Earth days to orbit the Sun. Rotation: A day on Mars lasts 24.6 hours. Its axial tilt of 25.2° gives it seasons similar to Earth\s',
        Natural_satellites: ' Mars has two small moons, Phobos and Deimos, likely captured asteroids',
        Magnetic_field: 'Mars has no global magnetic field but localized areas of crustal magnetism, suggesting it may have had one in the past',```
    },
    phobos: {
        semiMajorAxis: 0.0069,  // Unidade: milhões de km (aproximadamente 6,9 km)
        eccentricity: 0.0151,
        inclination: THREE.MathUtils.degToRad(1.08),
        longitudeOfAscendingNode: THREE.MathUtils.degToRad(113.68),
        argumentOfPeriapsis: THREE.MathUtils.degToRad(212.42),
        meanAnomalyAtEpoch: THREE.MathUtils.degToRad(236.0),
        epoch: 2451545.0,
        link: 'https://lh4.googleusercontent.com/proxy/_J0h01q8yY5_bB1jm52HTUYUgqKvM-O0XT86aVczsQLGApv0_pzwy_Y7R-SMro96-2CXcZuC0XjGtcJbX7E1EGcKqW0p4C86jwaFCaMRUPSObfljziHw',
        name: 'Phobos',
        sizeOf: '2', //1.5
        distance: '58 milhões de km'
    },
    deimos: {
        semiMajorAxis: 0.0235,  // Unidade: milhões de km (aproximadamente 23,5 km)
        eccentricity: 0.0007,
        inclination: THREE.MathUtils.degToRad(0.93),
        longitudeOfAscendingNode: THREE.MathUtils.degToRad(174.91),
        argumentOfPeriapsis: THREE.MathUtils.degToRad(122.38),
        meanAnomalyAtEpoch: THREE.MathUtils.degToRad(229.76),
        epoch: 2451545.0,
        link:'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/5938ae9e-47de-424a-8836-f98e6658d37b/dczaq88-d97d6ecd-a233-48a8-b1bc-74fd3327f95c.png/v1/fill/w_1264,h_632,q_70,strp/deimos_texture_map_by_askaniy_dczaq88-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MjA0OCIsInBhdGgiOiJcL2ZcLzU5MzhhZTllLTQ3ZGUtNDI0YS04ODM2LWY5OGU2NjU4ZDM3YlwvZGN6YXE4OC1kOTdkNmVjZC1hMjMzLTQ4YTgtYjFiYy03NGZkMzMyN2Y5NWMucG5nIiwid2lkdGgiOiI8PTQwOTYifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.hNuoyXLVNFXX4E21fnZN6hAhDAW1VPNBsNdDzYwmGhk',
        name: 'Deimos',
        sizeOf: '2', //0.004
        distance: '23,5 mil km'
    },
    
    jupter: {
        semiMajorAxis: 1430,
        eccentricity: 0.0565,
        inclination: THREE.MathUtils.degToRad(2.485),
        longitudeOfAscendingNode: THREE.MathUtils.degToRad(113.665),
        argumentOfPeriapsis: THREE.MathUtils.degToRad(336.313),
        meanAnomalyAtEpoch: THREE.MathUtils.degToRad(217.613),
        epoch: 2451545.0,
        link: 'https://www.reddit.com/media?url=https%3A%2F%2Fexternal-preview.redd.it%2FJJTceYLFNKh1trdhGTiDAku5dMw24H61e8xyi2_TS6g.jpg%3Fwidth%3D1080%26crop%3Dsmart%26auto%3Dwebp%26s%3D32e8236f46b72a2941c1f5a3fa0c1f2f7bd03ff7',
        name: 'Jupter',
        sizeOf: '10', //4.5
        distance: '1.2 bilhões de km'
    },

    saturn: {
        semiMajorAxis: 2000,
        eccentricity: 0.0565,
        inclination: THREE.MathUtils.degToRad(2.485),
        longitudeOfAscendingNode: THREE.MathUtils.degToRad(113.665),
        argumentOfPeriapsis: THREE.MathUtils.degToRad(336.313),
        meanAnomalyAtEpoch: THREE.MathUtils.degToRad(217.613),
        epoch: 2451545.0,
        link: 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/e0763947-6f42-4d09-944f-c2d6f41c415b/dcaift0-422ad564-f7b0-4291-914f-425b9ac29a35.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2UwNzYzOTQ3LTZmNDItNGQwOS05NDRmLWMyZDZmNDFjNDE1YlwvZGNhaWZ0MC00MjJhZDU2NC1mN2IwLTQyOTEtOTE0Zi00MjViOWFjMjlhMzUuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.YYTxK1xSwJxGTBIMLHsgFWiwrdd0W6UqmXy7a5CCnnk',
        sizeOf: '10',
        name: ```'Saturn',
        Size: 'Diameter of about 116,460 km, making Saturn the second-largest planet', //4.5
        Mass: 'About 5.68 x 10²⁶ kg, or 95 times Earth\s mass',
        Distance_from_the_Sun: ' About 1.43 billion km (9.58 AU)',
        Distance_from_Earth: ' Minimum distance is about 1.2 billion km',
        Composition: 'Saturn is composed mainly of hydrogen (96%) and helium (3%), similar to Jupiter, with no solid surface',
        Atmosphere: ' Saturn\s atmosphere is composed of hydrogen and helium, with cloud bands similar to Jupiter\s but less defined',
        Rings: 'Saturn is famous for its extensive ring system, composed of ice and rock particles',
        Orbit: ' Saturn takes 29.5 Earth years to orbit the Sun. Its day lasts about 10 hours and 33 minute',
        Natural_satellites: 'Saturn has 83 known moons, with notable ones including Titan, larger than Mercury, and Enceladus, which has icy geysers indicating a subsurface ocean',```

    }

};

export function createAllPlanets(textureLoader, scene) {
    var planets = [];
    var num  = 0;
    for (const planetName in orbitalElements) {
        const planet = createPlanet(orbitalElements[planetName].sizeOf, orbitalElements[planetName].link, 0x000000,textureLoader);
        planet.name = orbitalElements[planetName].name;
        planet.size = orbitalElements[planetName].sizeOf;
        planet.distance = orbitalElements[planetName].distance;
        planets.push(planet);
        scene.add(planet);
        let NomeParaAdicionar = document.getElementById("nome-do-planeta");
        NomeParaAdicionar.innerHTML = NomeParaAdicionar.innerHTML + `<option value="${num}">${planet.name}</option>`;
        num++;
        
    }
    planets[2].add(planets[3]);
    planets[3].position.set(2, 0, 0);

    planets[4].add(planets[5]);
    planets[5].position.set(1, 0, 0);

    planets[4].add(planets[6]);
    planets[6].position.set(2, 0, 0);

    return planets;
}